server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:foody.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

app:
  jwt:
    secret: 4f6f647944656c6976657279547261636b65725365637265744b6579466f7250726f6a656374
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
